name: .NET CI

on:
  push:
    branches: [ "master", "tests" ] # or "master", or any branch
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x # or whatever version your project uses

      - name: Restore dependencies
        run: dotnet restore VoxelForge.sln
        
      - name: Build
        run: dotnet build VoxelForge.sln --no-restore --configuration Debug --verbosity minimal

      - name: Run tests
        run: dotnet test VoxelForge.sln --configuration Debug --no-build --verbosity normal --logger "junit;LogFilePath=test-results.xml" --collect:"XPlat Code Coverage"
      
      - name: Report test results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: .Net Tests
          path: "**/test-results.xml"
          reporter: java-junit
      
      - name: Combine Coverage Reports
        uses: danielpalme/ReportGenerator-GitHub-Action@5.2.4
        with:
          reports: '**/*.cobertura.xml'
          targetdir: ${{ github.workspace }}
          reporttypes: 'Cobertura'
          verbosity: 'Info'
          title: "Code Coverage"
          tag: "${{ github.run_number }}_${{ github.run_id }}"
          toolpath: "reportgenerator"
      
      - name: Upload Combined Coverage XML
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage
          path: ${{ github.workspace }}/Cobertura.xml
          retention-days: 5
      
      - name: Publish Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: "**/Cobertura.xml"
          badge: true
          fail_below_min: false
          hide_complexity: false
          indicators: true
          output: both
          thresholds: '10 30'
      
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: "code-coverage-results.md"
          