name: .NET CI

on:
  push:
    branches: [ "master", "tests" ] # or "master", or any branch
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x # or whatever version your project uses

      - name: Restore dependencies
        run: dotnet restore VoxelForge.sln
        
      - name: Build
        run: dotnet build VoxelForge.sln --no-restore --configuration Debug --verbosity minimal

      - name: Run tests
        run: dotnet test VoxelForge.sln --configuration Debug --verbosity normal
